#ifndef _VERSION_H_
#define _VERSION_H_


#define WINAMPC_VERSION_MAJOR     ${WINAMPC_VERSION_MAJOR}
#define WINAMPC_VERSION_MINOR     ${WINAMPC_VERSION_MINOR}
#define WINAMPC_VERSION_BUILD     ${WINAMPC_VERSION_BUILD}
#define WINAMPC_VERSION_REVISION  ${WINAMPC_VERSION_REVISION}
#define WINAMPC_VERSION_STRING    "${WINAMPC_VERSION_MAJOR}.${WINAMPC_VERSION_MINOR}.${WINAMPC_VERSION_BUILD}"

#define WINAMPC_COPYRIGHT_YEARS_STRING   "2003-${CURRENT_YEAR}"


#endif   /* #ifndef _VERSION_H_ */
