#ifndef _VERSION_H_
#define _VERSION_H_


#define WINAMPC_VERSION_MAJOR     ${WINAMPC_VERSION_MAJOR}
#define WINAMPC_VERSION_MINOR     ${WINAMPC_VERSION_MINOR}
#define WINAMPC_VERSION_BUILD     ${WINAMPC_VERSION_BUILD}
#define WINAMPC_VERSION_REVISION  ${WINAMPC_VERSION_REVISION}

#define WINAMPC_VERSION_TEXT    ${WINAMPC_VERSION_TEXT}
#define WINAMPC_VERSION_STRING  ${WINAMPC_VERSION_STRING}

#define WINAMPC_COPYRIGHT_YEARS_TEXT     ${WINAMPC_COPYRIGHT_YEARS_TEXT}
#define WINAMPC_COPYRIGHT_YEARS_STRING   ${WINAMPC_COPYRIGHT_YEARS_STRING}


#endif   /* #ifndef _VERSION_H_ */
